site_name: RIT Racing Electronics Documentation
site_url: https://ritracingsoftware.github.io/ 
theme:
  name: material
  logo: assets/ritracing-white.png
  palette:
      scheme: slate
      primary: black
  features:
    - navigation.path
    - navigation.indexes 
    - navigation.tabs
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css
nav:
  - index.md

  - Hardware:
    - Altium:
      - Getting Started: Hardware/Altium/getting-started.md
    - MCU: General/MCU.md
    - Resources:
      - Hardware/Resources/learning.md
      - Silk Screen Files: Hardware/Resources/silk-screen-files.md
  - Firmware:
    - Firmware: Firmware/index.md
    - Firmware/resources.md
    - MCU: General/MCU.md
    - Core:
      - Firmware/Core/temp.md
    - IDE:
      - Firmware/IDE/temp.md
    - Projects:
      - Firmware/Projects/temp.md
  - General:
    - MCU: General/MCU.md
    - Protocols:
      - General/Protocols/index.md
  - Contribute:
    - Contribute/contribute.md