site_name: RIT Racing Electronics Documentation
site_url: https://ritracingsoftware.github.io/ 
theme:
  name: material
  logo: assets/ritracing-white.png
  palette:
      scheme: slate
      primary: black
  features:
    - navigation.path
    - navigation.indexes 
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - Hardware:
    - Hardware: Hardware/index.md
    - Hardware/resources.md
    - Altium:
      - Hardware/Altium/intro.md
    - MCU:
      - General/MCU/index.md
  - Firmware:
    - Firmware: Firmware/index.md
    - Firmware/resources.md
    - MCU:
      - MCU: General/MCU/index.md
    - Core:
      - Firmware/Core/temp.md
    - IDE:
      - Firmware/IDE/temp.md
    - Projects:
      - Firmware/Projects/temp.md
  - General:
    - MCU:
      - General/MCU/index.md
    - Protocols:
      - General/Protocols/index.md
  - Contribute:
    - Contribute/contribute.md
