site_name: RIT Racing Electronics Documentation
site_url: https://ritracingsoftware.github.io/ 
theme:
  name: material
  logo: assets/ritracing-white.png
  palette:
      scheme: slate
      primary: black
  features:
    - navigation.path
    - navigation.indexes 
    - navigation.tabs
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - Hardware:
    - Altium:
      - Get Altium: Hardware/Altium/get-altium.md
      - Project Setup: Hardware/Altium/project-setup.md
      - Schematic Basics: Hardware/Altium/schematic-basics.md
      - Library: Hardware/Altium/library.md
      - PCB Basics: Hardware/Altium/pcb-basics.md
      - Silkscreen Files: Hardware/Altium/silkscreen-files.md
    - MCU: Hardware/MCU.md
    - Resources: Hardware/resources.md
  - Firmware:
    - Firmware: Firmware/index.md
    - Firmware/resources.md
    - Core:
      - Firmware/Core/temp.md
    - Projects:
      - Firmware/Projects/temp.md
  - Contribute:
    - Contribute/contribute.md